apiVersion: v1
data: 
  default.conf: |
    server {
        listen       80;
        server_name  _;


        location / {
            proxy_pass {{ .Values.URL }};
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

        }
    }

kind: ConfigMap
metadata:
  name: nginx-conf-{{ .Values.Environment }}
  namespace: test-app-{{ .Values.Environment }}
