apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-{{ .Values.Environment }}
  name: nginx-{{ .Values.Environment }}
  namespace: test-app-{{ .Values.Environment }}
spec:
  ports:
    - name: "port80"
      port: 80
      targetPort: 80
      nodePort: {{ .Values.nodePort }}
  selector:
    app: nginx-{{ .Values.Environment }}
  type: NodePort
